# Generated by Django 5.2 on 2025-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_applications',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
