# Generated by Django 5.2 on 2025-04-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_max_applications"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_hired",
            field=models.BooleanField(default=False),
        ),
    ]
