# Generated by Django 5.2 on 2025-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_application_is_hired"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="hired_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
