services:
  jobboard:
    image: jobboard
    container_name: jobboard
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
